
- id: swiftstack_remove_swift_endpiont
  role: ['primary-controller']
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  type: shell
  parameters:
    cmd: ruby delete_entrypoint.rb
    timeout: 120

- id: swiftstack_configure_swift_endpoint
  role: ['primary-controller','controller']
  required_for: [post_deployment_end]
  requires: [post_deployment_start, swiftstack_remove_swift_endpiont]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster.pp
    puppet_modules: puppet/modules
    timeout: 420

