- id: swift-proxy_storage
  type: skipped
  version: 2.1.0
  role: ['/.*/']
  requires: [pre_deployment_start]

- id: swift-rebalance-cron
  type: skipped
  version: 2.1.0
  role: ['/.*/']
  requires: [pre_deployment_start]

- id: swift-keystone
  type: skipped
  version: 2.1.0
  role: ['/.*/']
  requires: [pre_deployment_start]

- id: openstack-haproxy-swift
  version: 2.1.0
  type: skipped
  role: ['/.*/']
  requires: [pre_deployment_start]

- id: upload_cirros
  version: 2.1.0
  type: skipped
  role: [primary-controller]
  requires: [pre_deployment_start]

- id: swiftstack-upload-cirros
  type: shell
  version: 2.1.0
  role: [primary-controller]
  requires: [swiftstack-tls-setup, swiftstack-enable-glance-backend, swiftstack-configure-swift-endpoint]
  required_for: [post_deployment_end]
  condition:
    yaql_exp: >
        $.swiftstack.upload_cirros_test
  parameters:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/astute/upload_cirros.rb
    retries: 5
    interval: 60
    timeout: 600

- id: swiftstack-tls-setup
  version: 2.1.0
  role: [primary-controller, controller, compute, compute-vmware, cinder, cinder-vmware, primary-mongo, mongo, ceph-osd, virt]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-tls-setup.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420

- id: swiftstack-configure-swift-endpoint
  version: 2.1.0
  role: [primary-controller]
  required_for: [post_deployment_end, swiftstack-enable-glance-backend]
  requires: [post_deployment_start,swiftstack-tls-setup]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-keystone.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420

- id: swiftstack-enable-glance-backend
  version: 2.1.0
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [post_deployment_start, swiftstack-tls-setup]
  cross-depends:
    - name: swiftstack-configure-swift-endpoint
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-glance.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420


