- id: swift
  version: 2.0.0
  type: skipped

- id: primary-swift
  version: 2.0.0
  type: skipped

- id: openstack-haproxy-swift
  version: 2.0.0
  type: skipped

- id: swift-rebalance-cron
  version: 2.0.0
  type: skipped

- id: swift-keystone
  version: 2.0.0
  type: skipped

- id: swift_zone
  version: 2.0.0
  type: skipped

- id: upload_cirros
  version: 2.0.0
  type: shell
  role: [primary-controller]
  condition: "settings:swiftstack.upload_cirros_test.value == true"

- id: swiftstack-tls-setup
  version: 2.0.0
  roles: [primary-controller, controller, compute, compute-vmware, cinder, cinder-vmware, primary-mongo, mongo, ceph-osd, virt]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-tls-setup.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420

- id: swiftstack-configure-swift-endpoint
  version: 2.0.0
  role: [primary-controller]
  required_for: [post_deployment_end, swiftstack-enable-glance-backend]
  requires: [post_deployment_start,swiftstack-tls-setup]
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-keystone.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420

- id: swiftstack-enable-glance-backend
  version: 2.0.0
  role: [primary-controller, controller]
  required_for: [post_deployment_end]
  requires: [post_deployment_start, swiftstack-tls-setup]
  cross-depends:
    - name: swiftstack-configure-swift-endpoint
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/sscluster-glance.pp
    puppet_modules: puppet/modules:/etc/puppet/modules/
    timeout: 420
