attributes:
  metadata:
    group: 'storage'
  swift_api_address:
    value: '192.168.1.100'
    label: 'Swift API IP Address'
    description: |
      If enabled, 
      * Swift deployment in controller nodes will be disabled
      * Swift API endpoint in Keysthone DB  will redirect to external Swift cluster.
    weight: 10
    type: "text"
    regex:
        source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
        error: "Invalid IP address"

#  upload_cirros_test:
#    weight: 20
#    type: "checkbox"
#    value: false
#    label: "Enable upload test"
#    description: "Upload cirros base image when the depoloyment is done"

